/* Demo seed data for The Byte Club API. Mirrors the storefront's mock catalog. */

export const categories = [
  { name: 'Burgers', slug: 'burgers', tagline: 'Stacked, sauced, structurally sound.', order: 1, image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=640&q=70&auto=format&fit=crop' },
  { name: 'Pizza', slug: 'pizza', tagline: 'Thin base, loud toppings.', order: 2, image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=640&q=70&auto=format&fit=crop' },
  { name: 'Fries & Sides', slug: 'fries', tagline: 'The supporting cast that steals the scene.', order: 3, image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=640&q=70&auto=format&fit=crop' },
  { name: 'Wraps', slug: 'wraps', tagline: 'Everything good, rolled tight.', order: 4, image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=640&q=70&auto=format&fit=crop' },
  { name: 'Sandwiches', slug: 'sandwiches', tagline: 'Toasted, pressed, non-negotiable.', order: 5, image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=640&q=70&auto=format&fit=crop' },
  { name: 'Shakes & Drinks', slug: 'beverages', tagline: 'Cold, thick, slightly show-off.', order: 6, image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=640&q=70&auto=format&fit=crop' },
  { name: 'Desserts', slug: 'desserts', tagline: 'The reward at the end of the queue.', order: 7, image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=640&q=70&auto=format&fit=crop' },
  { name: 'Combos', slug: 'combos', tagline: 'Full meal, one tap, less maths.', order: 8, image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=640&q=70&auto=format&fit=crop' },
];

const size = (deltas = [0, 60, 120]) => ({
  id: 'grp_size',
  name: 'Size',
  required: true,
  multiple: false,
  choices: [
    { id: 'size_reg', label: 'Regular', priceDelta: deltas[0], isDefault: true },
    { id: 'size_large', label: 'Large', priceDelta: deltas[1] },
    { id: 'size_mega', label: 'Mega Byte', priceDelta: deltas[2] },
  ],
});

const sauce = {
  id: 'grp_sauce',
  name: 'Sauce',
  required: true,
  multiple: false,
  choices: [
    { id: 'sauce_house', label: 'Byte house sauce', priceDelta: 0, isDefault: true },
    { id: 'sauce_smoky', label: 'Smoky chipotle', priceDelta: 15 },
    { id: 'sauce_garlic', label: 'Burnt garlic aioli', priceDelta: 15 },
  ],
};

const burgerAddOns = [
  { id: 'add_patty', label: 'Extra patty', price: 80 },
  { id: 'add_cheese', label: 'Extra cheese slice', price: 30 },
  { id: 'add_bacon', label: 'Smoked bacon', price: 60 },
  { id: 'add_jalapeno', label: 'Jalapeños', price: 20 },
  { id: 'add_fries', label: 'Side of fries', price: 90 },
];

export const products = [
  { name: 'The Classic Byte', slug: 'classic-byte', category: 'burgers', price: 229, isVeg: false, isBestseller: true, isFeatured: true, spiceLevel: 1, kcal: 640, prepTimeMins: 8, rating: 4.8, ratingCount: 512, description: 'Smashed beef patty, aged cheddar, house sauce, pickles, toasted brioche.', longDescription: 'Our origin story on a bun. A single 100g smash patty with lacy crisp edges, aged cheddar, shaved onion, dill pickles and the Byte house sauce on a toasted milk brioche.', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900&q=75&auto=format&fit=crop', ingredients: ['Beef patty', 'Brioche bun', 'Aged cheddar', 'House sauce', 'Pickles'], tags: ['beef', 'classic', 'bestseller'], optionGroups: [size(), sauce], addOns: burgerAddOns },
  { name: 'Double Stack Overflow', slug: 'double-stack-overflow', category: 'burgers', price: 319, isVeg: false, isBestseller: true, isFeatured: true, spiceLevel: 1, kcal: 920, prepTimeMins: 10, rating: 4.9, ratingCount: 388, description: 'Two smash patties, double cheese, caramelised onion, smoky mayo.', image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=900&q=75&auto=format&fit=crop', ingredients: ['2x Beef patty', 'Double cheese', 'Caramelised onion', 'Smoky mayo'], tags: ['beef', 'double', 'bestseller'], optionGroups: [size([0, 70, 140]), sauce], addOns: burgerAddOns },
  { name: 'Paneer Protocol', slug: 'paneer-protocol', category: 'burgers', price: 249, isVeg: true, isBestseller: true, isFeatured: false, spiceLevel: 2, kcal: 560, prepTimeMins: 9, rating: 4.7, ratingCount: 274, description: 'Chargrilled malai paneer slab, mint slaw, tandoori mayo, potato bun.', image: 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=900&q=75&auto=format&fit=crop', ingredients: ['Malai paneer', 'Mint slaw', 'Tandoori mayo', 'Potato bun'], tags: ['veg', 'paneer', 'spicy'], optionGroups: [size(), sauce], addOns: [{ id: 'add_paneer', label: 'Extra paneer', price: 70 }, { id: 'add_cheese', label: 'Cheese slice', price: 30 }, { id: 'add_fries', label: 'Side of fries', price: 90 }] },
  { name: 'Crispy Chick Commit', slug: 'crispy-chick-commit', category: 'burgers', price: 279, isVeg: false, isBestseller: true, isFeatured: true, spiceLevel: 2, kcal: 700, prepTimeMins: 11, rating: 4.8, ratingCount: 341, description: 'Buttermilk-fried chicken thigh, hot honey, pickles, slaw.', image: 'https://images.unsplash.com/photo-1615297928064-24977384d0da?w=900&q=75&auto=format&fit=crop', ingredients: ['Fried chicken thigh', 'Hot honey', 'Pickles', 'Slaw'], tags: ['chicken', 'fried', 'spicy', 'bestseller'], optionGroups: [size(), sauce], addOns: burgerAddOns },
  { name: 'Margherita Module', slug: 'margherita-module', category: 'pizza', price: 299, isVeg: true, isBestseller: false, isFeatured: true, spiceLevel: 0, kcal: 780, prepTimeMins: 12, rating: 4.6, ratingCount: 210, description: 'San Marzano sauce, fior di latte, basil, cold-pressed olive oil.', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=900&q=75&auto=format&fit=crop', ingredients: ['Sourdough base', 'San Marzano sauce', 'Fior di latte', 'Basil'], tags: ['veg', 'pizza', 'classic'], optionGroups: [{ id: 'grp_pizza_size', name: 'Size', required: true, multiple: false, choices: [{ id: 'psize_9', label: '9" personal', priceDelta: 0, isDefault: true }, { id: 'psize_12', label: '12" sharer', priceDelta: 160 }] }], addOns: [{ id: 'add_mush', label: 'Mushrooms', price: 45 }, { id: 'add_olives', label: 'Black olives', price: 40 }, { id: 'add_burrata', label: 'Burrata knob', price: 120 }] },
  { name: 'Pepperoni Packet', slug: 'pepperoni-packet', category: 'pizza', price: 379, isVeg: false, isBestseller: true, isFeatured: false, spiceLevel: 1, kcal: 940, prepTimeMins: 12, rating: 4.9, ratingCount: 305, description: 'Cupping pepperoni, spiced honey, mozzarella, chilli flakes.', image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=900&q=75&auto=format&fit=crop', ingredients: ['Sourdough base', 'Tomato sauce', 'Mozzarella', 'Pepperoni', 'Spiced honey'], tags: ['pork', 'pizza', 'bestseller'], optionGroups: [{ id: 'grp_pizza_size', name: 'Size', required: true, multiple: false, choices: [{ id: 'psize_9', label: '9" personal', priceDelta: 0, isDefault: true }, { id: 'psize_12', label: '12" sharer', priceDelta: 160 }] }], addOns: [{ id: 'add_pep', label: 'Extra pepperoni', price: 70 }, { id: 'add_jalapeno', label: 'Jalapeños', price: 25 }] },
  { name: 'Byte Fries', slug: 'byte-fries', category: 'fries', price: 129, isVeg: true, isBestseller: true, isFeatured: false, spiceLevel: 0, kcal: 380, prepTimeMins: 6, rating: 4.7, ratingCount: 620, description: 'Skin-on fries, Byte seasoning, house dip.', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=900&q=75&auto=format&fit=crop', ingredients: ['Potato', 'Byte seasoning', 'House dip'], tags: ['veg', 'fries', 'bestseller', 'shareable'], optionGroups: [size([0, 40, 80])], addOns: [{ id: 'add_cheesesauce', label: 'Molten cheese sauce', price: 45 }, { id: 'add_peri', label: 'Peri peri dust', price: 20 }] },
  { name: 'Kernel Panic Loaded Fries', slug: 'kernel-panic-loaded-fries', category: 'fries', price: 189, isVeg: true, isBestseller: false, isFeatured: true, spiceLevel: 1, kcal: 560, prepTimeMins: 8, rating: 4.8, ratingCount: 244, description: 'Fries under cheese sauce, jalapeños, crispy onions, herby drizzle.', image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=900&q=75&auto=format&fit=crop', ingredients: ['Fries', 'Cheese sauce', 'Jalapeños', 'Crispy onions'], tags: ['veg', 'fries', 'loaded', 'shareable'], optionGroups: [{ id: 'grp_protein', name: 'Top it', required: true, multiple: false, choices: [{ id: 'top_none', label: 'Keep it veg', priceDelta: 0, isDefault: true }, { id: 'top_chicken', label: 'Pulled chicken', priceDelta: 70 }, { id: 'top_beef', label: 'Chilli beef', priceDelta: 90 }] }], addOns: [{ id: 'add_cheesesauce', label: 'More cheese sauce', price: 45 }] },
  { name: 'Shawarma Stack Trace', slug: 'shawarma-stack-trace', category: 'wraps', price: 219, isVeg: false, isBestseller: true, isFeatured: false, spiceLevel: 2, kcal: 610, prepTimeMins: 7, rating: 4.8, ratingCount: 289, description: 'Spiced chicken, garlic toum, pickled slaw, saj wrap.', image: 'https://images.unsplash.com/photo-1633436375153-d7045cb93e38?w=900&q=75&auto=format&fit=crop', ingredients: ['Chicken thigh', 'Garlic toum', 'Pickled slaw', 'Saj wrap'], tags: ['chicken', 'wrap', 'bestseller'], optionGroups: [sauce], addOns: [{ id: 'add_toum', label: 'Extra toum', price: 20 }, { id: 'add_fries', label: 'Side of fries', price: 90 }] },
  { name: 'Falafel Fork', slug: 'falafel-fork', category: 'wraps', price: 189, isVeg: true, isBestseller: false, isFeatured: false, spiceLevel: 1, kcal: 480, prepTimeMins: 7, rating: 4.6, ratingCount: 132, description: 'Crunchy falafel, hummus, tahini, pickled turnip, herbs.', image: 'https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?w=900&q=75&auto=format&fit=crop', ingredients: ['Falafel', 'Hummus', 'Tahini', 'Pickled turnip'], tags: ['veg', 'vegan', 'wrap'], optionGroups: [], addOns: [{ id: 'add_falafel', label: 'Extra falafel', price: 45 }] },
  { name: 'The Byte Club Sandwich', slug: 'byte-club-sandwich', category: 'sandwiches', price: 259, isVeg: false, isBestseller: true, isFeatured: true, spiceLevel: 0, kcal: 720, prepTimeMins: 9, rating: 4.7, ratingCount: 198, description: 'Triple-decker: chicken, egg, streaky bacon, lettuce, tomato mayo.', image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=900&q=75&auto=format&fit=crop', ingredients: ['Sourdough', 'Roast chicken', 'Egg', 'Bacon', 'Lettuce'], tags: ['chicken', 'sandwich', 'bestseller'], optionGroups: [], addOns: [{ id: 'add_bacon', label: 'Extra bacon', price: 60 }, { id: 'add_egg', label: 'Extra egg', price: 25 }] },
  { name: 'Cache Melt', slug: 'cache-melt', category: 'sandwiches', price: 199, isVeg: true, isBestseller: false, isFeatured: false, spiceLevel: 0, kcal: 560, prepTimeMins: 7, rating: 4.6, ratingCount: 144, description: 'Four-cheese blend, cultured butter crust, tomato soup shot.', image: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=900&q=75&auto=format&fit=crop', ingredients: ['Sourdough', 'Four-cheese blend', 'Cultured butter', 'Tomato soup'], tags: ['veg', 'sandwich', 'cheese'], optionGroups: [], addOns: [{ id: 'add_chilli', label: 'Chilli jam', price: 25 }] },
  { name: 'Dark Mode Shake', slug: 'dark-mode-shake', category: 'beverages', price: 179, isVeg: true, isBestseller: true, isFeatured: true, spiceLevel: 0, kcal: 520, prepTimeMins: 4, rating: 4.9, ratingCount: 430, description: 'Dark chocolate, malt, cocoa crumb, torched marshmallow.', image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=900&q=75&auto=format&fit=crop', ingredients: ['Frozen custard', 'Dark chocolate', 'Malt', 'Marshmallow'], tags: ['veg', 'shake', 'bestseller', 'sweet'], optionGroups: [size([0, 40, 70])], addOns: [{ id: 'add_espresso', label: 'Espresso shot', price: 40 }, { id: 'add_brownie', label: 'Brownie chunk', price: 45 }] },
  { name: 'Berry 404 Cooler', slug: 'berry-404-cooler', category: 'beverages', price: 139, isVeg: true, isBestseller: false, isFeatured: false, spiceLevel: 0, kcal: 130, prepTimeMins: 3, rating: 4.5, ratingCount: 96, description: 'Mixed berries, lime, soda, mint — page not found, flavour is.', image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=900&q=75&auto=format&fit=crop', ingredients: ['Mixed berries', 'Lime', 'Mint', 'Soda'], tags: ['veg', 'vegan', 'drink'], optionGroups: [size([0, 30, 50])], addOns: [] },
  { name: 'Stack Trace Brownie', slug: 'stack-trace-brownie', category: 'desserts', price: 169, isVeg: true, isBestseller: true, isFeatured: false, spiceLevel: 0, kcal: 470, prepTimeMins: 4, rating: 4.9, ratingCount: 356, description: 'Fudge brownie, salted caramel, vanilla soft-serve, cocoa nib.', image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=900&q=75&auto=format&fit=crop', ingredients: ['Fudge brownie', 'Salted caramel', 'Vanilla soft-serve'], tags: ['veg', 'dessert', 'bestseller', 'sweet'], optionGroups: [], addOns: [{ id: 'add_scoop', label: 'Extra soft-serve', price: 40 }] },
  { name: 'Solo Run Combo', slug: 'solo-run-combo', category: 'combos', price: 379, isVeg: false, isBestseller: true, isFeatured: true, spiceLevel: 1, kcal: 1100, prepTimeMins: 12, rating: 4.7, ratingCount: 512, description: 'Any classic burger + Byte fries + a drink. One tap, one meal.', image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=900&q=75&auto=format&fit=crop', ingredients: ['1 classic burger', '1 regular fries', '1 drink'], tags: ['combo', 'value', 'bestseller'], optionGroups: [{ id: 'grp_combo_burger', name: 'Choose your burger', required: true, multiple: false, choices: [{ id: 'cb_classic', label: 'The Classic Byte', priceDelta: 0, isDefault: true }, { id: 'cb_paneer', label: 'Paneer Protocol', priceDelta: 20 }, { id: 'cb_chick', label: 'Crispy Chick Commit', priceDelta: 50 }] }, { id: 'grp_combo_drink', name: 'Choose your drink', required: true, multiple: false, choices: [{ id: 'cd_cola', label: 'Cola', priceDelta: 0, isDefault: true }, { id: 'cd_shake', label: 'Dark Mode Shake', priceDelta: 60 }] }], addOns: [{ id: 'add_dip', label: 'Extra dip', price: 25 }] },
];

export const offers = [
  { title: 'Buy 1 Get 1 — Classic Byte', description: 'Every Tuesday & Wednesday. Add two Classic Bytes, pay for one.', code: 'DOUBLECLICK', type: 'bogo', value: 100, image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=70&auto=format&fit=crop', accent: 'primary', badge: 'BOGO', isActive: true },
  { title: 'Student Rate — 20% off', description: 'Valid .edu email or a student ID at pickup.', code: 'CAMPUS20', type: 'percent', value: 20, minOrder: 199, image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=70&auto=format&fit=crop', accent: 'secondary', badge: 'STUDENT', isActive: true },
  { title: 'Weekend Combo Drop — ₹99 off', description: 'Flat ₹99 off any Combo, Sat & Sun.', code: 'WEEKEND99', type: 'flat', value: 99, minOrder: 349, image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=800&q=70&auto=format&fit=crop', accent: 'accent', badge: 'WEEKEND', isActive: true },
  { title: 'First Byte — ₹75 off your first order', description: '₹75 off when you spend ₹249+ on your first run.', code: 'FIRSTBYTE', type: 'flat', value: 75, minOrder: 249, image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=70&auto=format&fit=crop', accent: 'primary', badge: 'NEW', isActive: true },
  { title: 'Free shake over ₹699', description: 'Spend ₹699 and a Dark Mode Shake lands in your bag on the house.', type: 'freebie', value: 179, minOrder: 699, image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=70&auto=format&fit=crop', accent: 'secondary', badge: 'FREEBIE', isActive: true },
];

export const reviews = [
  { name: 'Ananya R.', handle: '@ananyaeats', rating: 5, productName: 'Double Stack Overflow', avatarColor: '#E2FF3C', body: 'The Double Stack Overflow is genuinely the best smash burger I have had in this city. Worth the walk.' },
  { name: 'Kabir M.', handle: '@kabirbytes', rating: 5, productName: 'Solo Run Combo', avatarColor: '#FF5C22', body: 'The Solo Run Combo is my desk lunch three days a week now. Dangerous.' },
  { name: 'Meera S.', handle: '@meerashots', rating: 4, productName: 'Paneer Protocol', avatarColor: '#FF2D6F', body: 'Paneer Protocol is a proper veg burger, not an afterthought.' },
  { name: 'Dev P.', handle: '@devp', rating: 5, productName: 'Kernel Panic Loaded Fries', avatarColor: '#E2FF3C', body: 'Loaded fries for the whole team on a release night. Still crunchy when they hit the table, which should not be physically possible.' },
  { name: 'Sara T.', handle: '@saratee', rating: 5, productName: 'Dark Mode Shake', avatarColor: '#FF5C22', body: 'Dark Mode Shake is thick enough that the straw stood up on its own.' },
];
